version: "3.8"

services:
  videoConversion:
    image: node:18-alpine
    container_name: videoConversion
    build: .
    environment:
      - NODE_ENV=production
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_GET_TOPIC=${KAFKA_GET_TOPIC}
      - KAFKA_RESULT_TOPIC=${KAFKA_RESULT_TOPIC}
      - ROLE_ARN=${ROLE_ARN}
      - REGION=${REGION}
      - INPUT_FILE=${INPUT_FILE}
      - OUTPUT_VIDEO=${OUTPUT_VIDEO}
      - OUTPUT_THUMBNAILS=${OUTPUT_THUMBNAILS}
      - OUTPUT_SUBTITLES=${OUTPUT_SUBTITLES}
      - SPEKE_URL=${SPEKE_URL}
      - REDIS_QUEUE_KEY=${REDIS_QUEUE_KEY}
      - PORT=9051
    ports:
      - "9051:9051"
    networks:
      - media_network
    env_file:
      - .env
    restart: unless-stopped

networks:
  media_network:
    driver: bridge