name: Auto Commit & Push

on:
  push:
    branches:
      - main

jobs:
  commit-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name:  Make Changes (Optional)
        run: |
          echo "// Auto-update timestamp" >> update.txt
          date >> update.txt

      - name:  Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update: $(date)" || echo "No changes to commit"
          git push origin main
